Excercise/Solution/Step 4/Axxes.Haxx/Axxes.Haxx.Web/Models/SessionViewModel.cs
using Axxes.Haxx.EntityFramework;
using System;
using System.Linq.Expressions;

namespace Axxes.Haxx.Web.Models
{
	public class SessionViewModel
	{
		public int Id { get; set; }
		public string Title { get; set; }
		public DateTime DateTime { get; set; }
		public string Category { get; set; }
		public string Speaker { get; set; }

		public static Expression<Func<Session, SessionViewModel>> ViewModel
		{
			get 
			{
				return s => new SessionViewModel
				{
					Id = s.Id,
					Title = s.Title,
					DateTime = s.DateTime,
					Category = s.Category,
					Speaker = s.Speaker.FullName
				};
			}
		}
	}
}

Excercise/Solution/Step 4/Axxes.Haxx/Axxes.Haxx.Web/Controllers/SessionController.cs
using Axxes.Haxx.EntityFramework;
using Axxes.Haxx.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace Axxes.Haxx.Web.Controllers
{
	[Authorize]
	public class SessionController : BaseController
	{
		public SessionController(ApplicationDbContext db, UserManager<ApplicationUser> userManager) : base(db, userManager)
		{
		}

		public IActionResult CreateSession()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult CreateSession(SessionInputModel model)
		{
			if (model != null && ModelState.IsValid)
			{
				var session = new Session
				{
					SpeakerId = UserManager.GetUserId(this.User),
					Title = model.Title,
					DateTime = model.DateTime,
					Category = model.Category,
					Description = model.Description,
					IsPublic = model.IsPublic
				};

				this.Db.Sessions.Add(session);
				this.Db.SaveChanges();
				return RedirectToAction("MySessions");
			}

			return View(model);
		}

		public IActionResult MySessions()
		{
			var currentUserId = UserManager.GetUserId(this.User);
			var sessions = Db.Sessions
				.Where(s => s.SpeakerId == currentUserId)
				.OrderBy(s => s.DateTime)
				.Select(SessionViewModel.ViewModel);

			var upcommingSessions = sessions.Where(s => s.DateTime > DateTime.Now);
			var passedSessions = sessions.Where(s => s.DateTime <= DateTime.Now);

			return View(new UpcomingPassedSessionViewModel
			{
				PassedSessions = passedSessions,
				UpcommingSessions = upcommingSessions
			});
		}

		public IActionResult Edit(int id)
		{
			var session = LoadSession(id);
			if (session == null) 
			{
				return RedirectToAction("MySessions");
			}

			var model = SessionInputModel.CreateSessionInputModel(session);

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(int id, SessionInputModel model)
		{
			if (model != null && ModelState.IsValid)
			{
				var session = LoadSession(id);
				session.Title = model.Title;
				session.DateTime = model.DateTime;
				session.Category = model.Category;
				session.Description = model.Description;
				session.IsPublic = model.IsPublic;
				this.Db.SaveChanges();
				return RedirectToAction("MySessions");
			}

			return View(model);
		}

		private Session LoadSession(int id) 
		{
			var currentUserId = UserManager.GetUserId(this.User);
			var isAdmin = IsAdmin();
			var session = Db.Sessions
				.Where(s => s.Id == id)
				.FirstOrDefault(s => s.SpeakerId == currentUserId || isAdmin);
			return session;
		}
	}
}

Excercise/Solution/Step 4/Axxes.Haxx/Axxes.Haxx.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Axxess Conference System</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Axxes.Haxx.Web</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sessions</a>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<partial name="_LoginPartial" />
					<ul class="navbar-nav flex-grow-1">
						@if (User.Identity.IsAuthenticated)
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="CreateSession">Create session</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="MySessions">My sessions</a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2020 - Axxes Conference System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

Excercise/Solution/Step 4/Axxes.Haxx/Axxes.Haxx.Web/Views/Shared/_Sessions.cshtml
@model UpcomingPassedSessionViewModel

<h1 class="session-group-heading">Upcomming sessions</h1>
<div class="row">
	@if (Model.UpcommingSessions.Any())
	{
		@Html.DisplayFor(x => x.UpcommingSessions);
	}
	else
	{
		<div>No sessions.</div>
	}
</div>

<h1 class="session-group-heading">Passed sessions</h1>
<div class="row">
	@if (Model.PassedSessions.Any())
	{
		@Html.DisplayFor(x => x.PassedSessions);
	}
	else
	{
		<div>No sessions.</div>
	}
</div>